siteblog/blog/urls.py
from django.urls import path

from .views import *



urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('category/<str:slug>/', PostByCategory.as_view(), name='category'),
    path('tag/<str:slug>/', PostByTag.as_view(), name='tag'),
    path('post/<str:slug>/', GetPost.as_view(), name='post'),
    path('search/', Search.as_view(), name='search'),
    path('zastavka/', zastavka),
    # path('send_email/', send_email, name='send_email'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('review/<int:pk>/', AddReview.as_view(), name='add_comment'),
]

siteblog/siteblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteblog/blog/models.py
from django.db import models
from django.urls import reverse

'''
Category
=========
title, slug

Tag
=========
title, slug

Post
=========
title, slug, author, content, created_at, photo, views, category, tags
'''


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название категори')
    slug = models.SlugField(max_length=255, verbose_name='Url Category', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'
        ordering = ['title']


class Tag(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название Тэга')
    slug = models.SlugField(max_length=50, verbose_name='Url Tag', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tag', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = "Теги"
        ordering = ['title']


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(max_length=255, verbose_name='Url', unique=True)
    author = models.CharField(max_length=100, verbose_name='Автор')
    content = models.TextField(blank=True, verbose_name='Контент')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='posts', verbose_name='Категория')
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts', verbose_name='тЭги')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = "Посты"
        ordering = ['-created_at']


class Zastavka(models.Model):
    foto = models.ImageField(upload_to='zastavka', blank=True, verbose_name='Картинка')
    nazvanie = models.CharField(max_length=50, verbose_name='Название')
    opisanie = models.CharField(max_length=150, verbose_name='Описание')

    def __str__(self):
        return self.nazvanie

    # def get_absolute_url(self):
    #     return reverse('zastavka', kwargs={'slug': self.slug})
    #
    class Meta:
        verbose_name = 'Заставка'
        verbose_name_plural = "Заставки"
        # ordering = ['nazvanie']


class Contact(models.Model):
    """Подписка на email"""
    name = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=50)
    # last_send = models.DateTimeField(auto_now=True, verbose_name='Последняя рассылка')

    def __str__(self):
        return self.email


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Коментарий", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    post = models.ForeignKey(Post, verbose_name="Пост", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.post}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

siteblog/blog/forms.py
from django import forms
from .models import Contact, Reviews


class ContactForm(forms.ModelForm):
    """Форма подписки по email"""
    class Meta:
        model = Contact
        fields = '__all__'


class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')



# class ContactEmail(forms.Form):
#     name = forms.CharField(max_length=30, label='Имя', required=False)
#     email = forms.EmailField(max_length=50, label='Почта')

siteblog/blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import FormMixin
from .tasks import send_spam_email
from .models import *
from .forms import ContactForm, ReviewForm
from .service import send
from django.db.models import F


class Home(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Космос'
        return context


class PostByCategory(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Category.objects.get(slug=self.kwargs['slug'])
        return context


class PostByTag(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Записи по тегу: ' + str(Tag.objects.get(slug=self.kwargs['slug']))
        return context


class GetPost(FormMixin, DetailView):
    model = Post
    form_class = ContactForm
    template_name = 'blog/single.html'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object.views = F('views') + 1
        self.object.save()
        self.object.refresh_from_db()
        return context


class Search(ListView):
    template_name = 'blog/search.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        return Post.objects.filter(title__icontains=self.request.GET.get('s'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['s'] = f"s={self.request.GET.get('s')}&"
        return context


# def index(request):
#     zastavka = Zastavka.objects.get(id=1)
#     return render(request, 'blog/index.html', {'zAsTaVkA': zastavka,)


def zastavka(request):
    zastavka = Zastavka.objects.all()
    return render(request, 'blog/zastavka.html', {'zAsTaVkA': zastavka, 'nazvanie': 'Заставка'})

#
# def contact(request):
#     return render(request, 'blog/contact.html')


class ContactView(CreateView):
    """Отображение формы подписки по email"""
    model = Contact
    form_class = ContactForm
    success_url = '/'
    template_name = 'blog/single.html'

    def form_valid(self, form):
        form.save()
        # send(form.instance.email)
        send_spam_email.delay(form.instance.email)
        return super().form_valid(form)


class AddReview(View):
    """Коментарии"""
    def post(self, request, pk):
        print(request.POST)
        form = ReviewForm(request.POST)
        post = Post.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.post = post
            form.save()
        return redirect(post.get_absolute_url())

siteblog/blog/templates/blog/category.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="bg-text-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="bg-text">
                    <h3>Classic BLOG Design</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="blog-post-area">
    <div class="container">
        <div class="row">
            <div class="blog-post-area-style">
                <div class="col-md-12">
                    <div class="single-post-big">
                        <div class="big-image">
                            <img src='{% static "img/post-image1.jpg" alt="" %}'>
                        </div>
                        <div class="big-text">
                            <h3><a href="#">Post Title Goes Here.</a></h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                                exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.eiusmod tempor
                                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                            <h4><span class="date">25 February 2017</span><span class="author">Posted By: <span
                                    class="author-name">Kabbo Liate</span></span>
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-post">
                        <img src='{% static "img/post-image2.jpg" alt="" %}'>
                        <h3><a href="#">Post Title Goes Here.</a></h3>
                        <h4><span>Posted By: <span class="author-name">Kabbo Liate</span></span>
                        </h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed dotempor incididunt ut. labore
                            et dolore magna aliqua. Ut enim ad minim veniam</p>
                        <h4><span>25 February 2017</span></h4>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-post">
                        <img src='{% static "img/post-image3.jpg" alt="" %}'>
                        <h3><a href="#">Post Title Goes Here.</a></h3>
                        <h4><span>Posted By: <span class="author-name">Kabbo Liate</span></span>
                        </h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed dotempor incididunt ut. labore
                            et dolore magna aliqua. Ut enim ad minim veniam</p>
                        <h4><span>25 February 2017</span></h4>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-post">
                        <img src='{% static "img/post-image4.jpg" alt="" %}'>
                        <h3><a href="#">Post Title Goes Here.</a></h3>
                        <h4><span>Posted By: <span class="author-name">Kabbo Liate</span></span>
                        </h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed dotempor incididunt ut. labore
                            et dolore magna aliqua. Ut enim ad minim veniam</p>
                        <h4><span>25 February 2017</span></h4>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-post">
                        <img src='{% static "img/post-image5.jpg" alt="" %}'>
                        <h3><a href="#">Post Title Goes Here.</a></h3>
                        <h4><span>Posted By: <span class="author-name">Kabbo Liate</span></span>
                        </h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed dotempor incididunt ut. labore
                            et dolore magna aliqua. Ut enim ad minim veniam</p>
                        <h4><span>25 February 2017</span></h4>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-post">
                        <img src='{% static "img/post-image6.jpg" alt="" %}'>
                        <h3><a href="#">Post Title Goes Here.</a></h3>
                        <h4><span>Posted By: <span class="author-name">Kabbo Liate</span></span>
                        </h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed dotempor incididunt ut. labore
                            et dolore magna aliqua. Ut enim ad minim veniam</p>
                        <h4><span>25 February 2017</span></h4>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-post">
                        <img src='{% static "img/post-image7.jpg" alt="" %}'>
                        <h3><a href="#">Post Title Goes Here.</a></h3>
                        <h4><span>Posted By: <span class="author-name">Kabbo Liate</span></span>
                        </h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed dotempor incididunt ut. labore
                            et dolore magna aliqua. Ut enim ad minim veniam</p>
                        <h4><span>25 February 2017</span></h4>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-post">
                        <img src='{% static "img/post-image8.jpg" alt="" %}'>
                        <h3><a href="#">Post Title Goes Here.</a></h3>
                        <h4><span>Posted By: <span class="author-name">Kabbo Liate</span></span>
                        </h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed dotempor incididunt ut. labore
                            et dolore magna aliqua. Ut enim ad minim veniam</p>
                        <h4><span>25 February 2017</span></h4>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-post">
                        <img src='{% static "img/post-image9.jpg" alt="" %}'>
                        <h3><a href="#">Post Title Goes Here.</a></h3>
                        <h4><span>Posted By: <span class="author-name">Kabbo Liate</span></span>
                        </h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed dotempor incididunt ut. labore
                            et dolore magna aliqua. Ut enim ad minim veniam</p>
                        <h4><span>25 February 2017</span></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pegination">


        <div class="nav-links">
            <span class="page-numbers current">1</span>
            <a class="page-numbers" href="#">2</a>
            <a class="page-numbers" href="#">3</a>
            <a class="page-numbers" href="#">4</a>
            <a class="page-numbers" href="#">5</a>
            <a class="page-numbers" href="#"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
        </div>
    </div>
</section>

{% endblock %}

siteblog/blog/templates/blog/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Подписка</title>
</head>
<body>

<div class="newsletter">
    <h2 class="sidebar-title">Подписывайтесь на новые новости</h2>
    <form action="{% url 'contact' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Подписаться">
    </form>
</div>

</body>
</html>

siteblog/blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }} :: {{ block.super}}{% endblock %}

{% block content %}


{% include 'blog/zastavka.html' %}

<section class="blog-post-area">
    <div class="container">
        <div class="row">
            <div class="blog-post-area-style">


                {% for post in posts %}
                <div class="col-md-3">
                    <div class="single-post">

                        {% if post.photo %}
                        <img src="{{ post.photo.url }}" alt="{{ post.title }}">
                        {% else %}
                        <img src="https:picsum.photos/id/1060/300/201/?blur=2" alt="{{ post.title }}">
                        {% endif %}

                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                        <h4><span>Posted By: <span class="author-name">{{ post.author }}</span></span>
                        </h4>
                        {{ post.content|truncatewords_html:20|safe }}
                        <h4><span>{{ post.created_at|date:"j E Y" }}</span></h4>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if page_obj.has_other_pages %}
    <div class="pegination">
        <div class="nav-links">
            {% if page_obj.has_previous %}
            <a class="page-numbers" href="?page={{ page_odj.previous_page_number }}"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
            {% endif %}

            {% for p in page_obj.paginator.page_range %}
                {% if page_obj.number == p %}
                <span class="page-numbers current">{{ p }}</span>
                {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                <a class="page-numbers" href="?page={{ p }}">{{ p }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <a class="page-numbers" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            {% endif %}
        </div>
    </div>
    {% endif %}
</section>

{% endblock %}

siteblog/blog/templates/blog/menu_tpl.html
<div class="{{ menu_class }}">
    <ul>
        <li><a href="{% url 'home' %}">Домой</a></li>
        {% for item in categories %}
        <li><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></li>
        {% endfor %}
    </ul>
</div>

siteblog/blog/templates/blog/popular_posts_tpl.html
<h2 class="sidebar-title">Popular posts</h2>
<div class="grid">
    {% for post in posts %}
    <div class="portfolio-item popular">
        {% if post.photo %}
        <img src="{{ post.photo.url }}" alt="{{ post.title }}">
        {% else %}
        <img src="https:picsum.photos/id/1060/300/201/?blur=2" alt="{{ post.title }}">
        {% endif %}

        <div class="portfolio-text">
            <h5><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
            <p>{{ post.author }}<span>|</span>{{ post.created_at|date:"d.m.Y" }}</p>
        </div>
    </div>
    {% endfor %}
</div>

siteblog/blog/templates/blog/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Поиск :: {{ block.super}}{% endblock %}

{% block content %}


<section class="blog-post-area">
    <div class="container">
        <div class="border-top" style="border-top: 1px solid #40c4ff;"></div>
        <div class="row">
            <div class="blog-post-area-style">

                {% for post in posts %}
                <div class="col-md-3">
                    <div class="single-post">

                        {% if post.photo %}
                        <img src="{{ post.photo.url }}" alt="{{ post.title }}">
                        {% else %}
                        <img src="https:picsum.photos/id/1060/300/201/?blur=2" alt="{{ post.title }}">
                        {% endif %}

                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                        <h4><span>Posted By: <span class="author-name">{{ post.author }}</span></span>
                        </h4>
                        {{ post.content|truncatewords_html:20|safe }}
                        <h4><span>{{ post.created_at|date:"j E Y" }}</span></h4>
                    </div>
                </div>
                {% empty %}
                <p>По вашему запросу ничего не найдено</p>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if page_obj.has_other_pages %}
    <div class="pegination">
        <div class="nav-links">

            {% for p in page_obj.paginator.page_range %}
                {% if page_obj.number == p %}
                <span class="page-numbers current">{{ p }}</span>
                {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                <a class="page-numbers" href="?{{ s }}page={{ p }}">{{ p }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <a class="page-numbers" href="?{{ s }}page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            {% endif %}
        </div>
    </div>
    {% endif %}
</section>

{% endblock %}

siteblog/blog/templates/blog/send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Подписка</h1>

<form action="{% url 'send_email' %}" method="post">

    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary btn-block">Подписаться</button>
</form>

</body>
</html>

siteblog/blog/templates/blog/single.html
{% extends 'base.html' %}
{% load static %}
{% load sidebar %}

{% block title %}{{ post.title }} :: {{ block.super}}{% endblock %}

{% block content %}

<section class="single-blog-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="border-top">
                    <div class="col-md-8">
                        <div class="blog-area">
                            <div class="blog-area-part">
                                <h2>{{ post.title }}</h2>
                                <div class="single-content">
                                    <div>
                                        <span> =) Знания дарованны : {{ post.author }}</span>
                                        <br>
                                        <span>Ккатегория: <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a> </span>
                                        <br>
                                        {% if post.tags.exists %}
                                        <span>тЭги:
                                            {% for tag in post.tags.all %}
                                            <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
                                            {% endfor %}
                                        </span>
                                        <br>
                                        {% endif %}
                                        <span>Просмотров: {{ post.views }}</span>
                                    </div>
                                    {{post.content|safe}}
                                </div>
                            </div>

                            <div class="commententries">
                                <h3>Comments</h3>

                                <ul class="commentlist">
                                    {% for review in post.reviews_set.all %}
                                    <li>
                                        <article class="comment">
                                            <header class="comment-author">
                                                <img src="{% static 'img/author-2.jpg' %}" alt="">
                                            </header>
                                            <section class="comment-details">
                                                <div class="author-name">
                                                    <h5><a href="#">{{ review.name }}</a></h5>
                                                </div>
                                                <div class="comment-body">
                                                    <p>{{ review.text}} </p>
                                                </div>
                                            </section>
                                        </article>

<!--                                        <ul class="children">-->
<!--                                            <li>-->
<!--                                                <article class="comment">-->
<!--                                                    <header class="comment-author">-->
<!--                                                        <img src="img/author-2.jpg" alt="">-->
<!--                                                    </header>-->
<!--                                                    <section class="comment-details">-->
<!--                                                        <div class="author-name">-->
<!--                                                            <h5><a href="#">Khalid Hasan Zibon</a></h5>-->
<!--                                                            <p>February 25 2017</p>-->
<!--                                                        </div>-->
<!--                                                        <div class="comment-body">-->
<!--                                                            <p>is simply dummy text of the printing and typesetting-->
<!--                                                                industry. Lorem Ipsum has been the industry's-->
<!--                                                                standard </p>-->
<!--                                                        </div>-->
<!--                                                        <div class="reply">-->
<!--                                                            <p><span><a href="#"><i class="fa fa-thumbs-up"-->
<!--                                                                                    aria-hidden="true"></i></a>12</span><span><a-->
<!--                                                                    href="#"><i class="fa fa-reply"-->
<!--                                                                                aria-hidden="true"></i></a>7</span></p>-->
<!--                                                        </div>-->
<!--                                                    </section>-->
<!--                                                </article>-->
<!--                                            </li>-->
<!--                                        </ul>-->

                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <form action="{% url 'add_comment' post.id %}" method="post" id="formReview">
                                {% csrf_token %}
                                <div class="name">
                                    <input type="text" name="name" id="" placeholder="Name" class="name">
                                </div>
                                <div class="email">
                                    <input type="email" name="email" id="" placeholder="Email" class="email">
                                </div>
                                <div class="comment">
                                    <input type="text" name="text" id="" placeholder="Comment" class="comment">
                                </div>
                                <div class="post">
                                    <input type="submit" value="Post">
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-4">

                        <div class="newsletter">
                            <h2 class="sidebar-title">Поиск</h2>
                            <form action="{% url 'search' %}" method="get">
                                <input type="text" name="s" placeholder="Найти ...">
                                <input type="submit" value="Искать">
                            </form>
                        </div>

                        <hr>

                        {% include 'blog/contact.html' %}

                        <hr>

                        {% get_popular 3 %}

                        {% get_tags %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

siteblog/blog/templates/blog/tags_tpl.html
<div class="tags">
    <h2 class="sidebar-title">Tags</h2>
    {% for tag in tags %}
    <p><a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a></p>
    {% endfor %}
</div>

siteblog/blog/templates/blog/zastavka.html
<!doctype html>
{% load zastavka %}
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Заставка</title>
  </head>
  <body>


<div class="container mb-3">
    <h1>ЗАГОЛОВОК =)</h1>
    {% zas as zAsTaVkA %}
    <div class="card bg-dark text-white">
        {% for x in zAsTaVkA %}
        <img src="{{ x.foto.url }}" height="300" class="card-img">
        <div class="card-img-overlay">
            <h1 class="card-title">{{ x.nazvanie }}</h1>
            <p class="card-text"><h1>{{ x.opisanie }}</h1></p>
        </div>
        {% endfor %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>